export const siteFacts = {
  updatedDate: "2026-06-19",
  updatedLabel: "June 19, 2026",
  appStoreUrl: "https://apps.apple.com/us/app/wearra-ai-outfit-planner/id6761031400",
  appStoreId: "6761031400",
  appStoreName: "Wearra: AI Outfit Planner",
  appCategory: "Lifestyle",
  secondaryGenre: "Productivity",
  minimumOS: "iOS 18.0",
  homepageTitle: "Wearra — Digital Closet, AI Outfit Planner & Virtual Try-On",
  homepageDescription: "Organize clothes you own, get personalized outfit ideas, plan your week, build smarter travel packing lists, and preview outfits on your own photo with Wearra.",
  homepageH1: "Your AI outfit planner and digital closet.",
  homepageSubheading: "Organize clothes you own, get personalized outfit ideas, plan your week, pack smarter, and use Try On credits to preview outfits on your own photo.",
  priceText: "Free download",
  pricingNote: "Wearra is free to download. Try On requires Pro, bonus credits, or a render pack.",
  proPrice: "$6.99",
  proPriceValue: "6.99",
  proRenderAllowance: "30",
  topUpPrice: "$1.99",
  topUpPriceValue: "1.99",
  topUpRenderAllowance: "5"
};
